import re
import streamlit as st
import pandas as pd
from datetime import datetime
from common import parse_ddl, parse_yaml_schema, run_agent

st.markdown('<div class="step-label">⬡ Schema Input & Generation</div>', unsafe_allow_html=True)

col1, col2 = st.columns([1, 1], gap="large")

with col1:
    st.markdown('<div class="step-label">⬡ Step 1 — Define Your Schema</div>', unsafe_allow_html=True)
    schema_type = st.selectbox("Schema Format", ["SQL DDL", "YAML"])

    ddl_example = """CREATE TABLE employees (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(150),
    phone VARCHAR(15),
    gender VARCHAR(10),
    job_title VARCHAR(100),
    department VARCHAR(50),
    salary DECIMAL(10,2),
    hire_date DATE,
    city VARCHAR(50),
    country VARCHAR(50),
    is_active BOOLEAN
);"""

    yaml_example = """table_name: employees
columns:
  - name: id
    type: integer
    primary_key: true
  - name: name
    type: string
  - name: email
    type: email
  - name: phone
    type: phone
  - name: gender
    type: string
    values: [Male, Female]
  - name: job_title
    type: string
  - name: department
    type: string
    values: [HR, Engineering, Finance, Marketing, Sales]
  - name: salary
    type: decimal
    min: 30000
    max: 200000
  - name: hire_date
    type: date
  - name: city
    type: city
  - name: country
    type: string
  - name: is_active
    type: boolean"""

    schema_input = st.text_area(
        "Paste your schema here",
        value=ddl_example if schema_type == "SQL DDL" else yaml_example,
        height=300
    )

    st.markdown('<div class="step-label">⬡ Step 2 — Configure Settings</div>', unsafe_allow_html=True)
    num_rows = st.number_input("Number of rows to generate", min_value=5, max_value=500, value=20)
    if "use_llm" not in st.session_state:
        st.session_state["use_llm"] = False
    use_llm = st.session_state["use_llm"]
    if use_llm:
        st.caption("🤖 Ollama LLM enabled (configured in Settings)")
    else:
        st.caption("⚡ Faker mode active — go to Settings to enable Ollama LLM")
    generate_btn = st.button("⚡ Generate Mock Data")

with col2:
    st.markdown('<div class="step-label">⬡ Step 3 — Agent Log & Results</div>', unsafe_allow_html=True)
    log_placeholder = st.empty()

    if generate_btn:
        if not schema_input.strip():
            st.error("⚠️ Please enter a schema.")
        else:
            try:
                table_name = "generated_table"
                if schema_type == "SQL DDL":
                    columns = parse_ddl(schema_input)
                    match = re.search(r'CREATE TABLE\s+(\w+)', schema_input, re.IGNORECASE)
                    if match:
                        table_name = match.group(1)
                    for col in columns:
                        col.setdefault('values', None)
                        col.setdefault('min', None)
                        col.setdefault('max', None)
                        col.setdefault('primary_key', col['name'].lower() == 'id')
                else:
                    columns, table_name = parse_yaml_schema(schema_input)

                if not columns:
                    st.error("❌ Could not detect any columns. Check your schema format.")
                else:
                    rows = run_agent(columns, num_rows, table_name, log_placeholder, use_llm)
                    col_names = [c['name'] for c in columns]
                    df = pd.DataFrame(rows, columns=col_names)

                    st.markdown(f'<div class="success-box">✅ Agent generated <strong>{len(df)} rows</strong> with <strong>{len(df.columns)} columns</strong> successfully!</div>', unsafe_allow_html=True)
                    st.dataframe(df, use_container_width=True, height=250)

                    st.markdown("### 📥 Download")
                    dl1, dl2 = st.columns(2)

                    csv_data = df.to_csv(index=False)
                    dl1.download_button("⬇️ Download CSV", data=csv_data,
                        file_name=f"mock_data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
                        mime="text/csv")

                    sql_lines = [
                        f"-- Mock Data Generated by Team 14 Mock Data Generator Agent",
                        f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                        f"-- Table: {table_name} | Rows: {len(df)}\n"
                    ]
                    for _, row in df.iterrows():
                        vals = []
                        for v in row:
                            if v is None or (isinstance(v, float) and pd.isna(v)):
                                vals.append("NULL")
                            elif isinstance(v, bool):
                                vals.append("TRUE" if v else "FALSE")
                            elif isinstance(v, (int, float)):
                                vals.append(str(v))
                            else:
                                vals.append(f"'{str(v).replace(chr(39), chr(39)*2)}'")
                        sql_lines.append(f"INSERT INTO {table_name} ({', '.join(col_names)}) VALUES ({', '.join(vals)});")

                    dl2.download_button("⬇️ Download SQL", data="\n".join(sql_lines),
                        file_name=f"mock_data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.sql",
                        mime="text/plain")

                    s1, s2, s3 = st.columns(3)
                    s1.metric("Rows Generated", len(df))
                    s2.metric("Columns", len(df.columns))
                    s3.metric("Table", table_name)

            except Exception as e:
                st.error(f"❌ Error: {str(e)}")
    else:
        st.markdown("""
        <div style="background:linear-gradient(135deg,#111827,#0b1120);border:1px solid #1e293b;border-radius:16px;padding:4rem 2rem;text-align:center;box-shadow:0 8px 32px rgba(0,0,0,0.4);">
            <div style="font-size:4rem;margin-bottom:1rem;filter:drop-shadow(0 0 20px rgba(168,85,247,0.3));">🗄️</div>
            <div style="color:#22d3ee;font-size:0.7rem;font-weight:700;letter-spacing:0.15em;text-transform:uppercase;margin-bottom:0.5rem;">READY TO GENERATE</div>
            <div style="color:#94a3b8;font-size:0.95rem;line-height:1.6;">
                Paste your schema on the left<br>set number of rows<br>and click <strong style="color:#d8b4fe;font-size:1rem;">⚡ Generate Mock Data</strong>
            </div>
            <div style="margin-top:1.5rem;display:flex;justify-content:center;gap:1rem;flex-wrap:wrap;">
                <span style="background:#111827;border:1px solid #1e293b;border-radius:999px;padding:0.3rem 0.8rem;color:#94a3b8;font-size:0.75rem;">SQL DDL</span>
                <span style="background:#111827;border:1px solid #1e293b;border-radius:999px;padding:0.3rem 0.8rem;color:#94a3b8;font-size:0.75rem;">YAML</span>
                <span style="background:#111827;border:1px solid #1e293b;border-radius:999px;padding:0.3rem 0.8rem;color:#94a3b8;font-size:0.75rem;">CSV Export</span>
                <span style="background:#111827;border:1px solid #1e293b;border-radius:999px;padding:0.3rem 0.8rem;color:#94a3b8;font-size:0.75rem;">SQL Export</span>
            </div>
        </div>
        """, unsafe_allow_html=True)
